# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('rpc', '0002_auto_20160419_2219'), ('rpc', '0003_auto_20160424_2103'), ('rpc', '0004_auto_20160424_2120')]

    dependencies = [
        ('rpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfcStateSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_iana_flag', models.NullBooleanField()),
                ('old_ref_flag', models.NullBooleanField()),
                ('old_version_number', models.IntegerField(null=True)),
                ('iana_flag', models.NullBooleanField()),
                ('ref_flag', models.NullBooleanField()),
                ('version_number', models.IntegerField(null=True)),
                ('days', models.PositiveSmallIntegerField()),
                ('oldstate', models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oldstate', to='rpc.States')),
                ('rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpc.Index')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpc.States')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rfcstatesummary',
            unique_together=set([('rfc', 'oldstate', 'state', 'old_version_number', 'version_number', 'old_iana_flag', 'old_ref_flag', 'iana_flag', 'ref_flag')]),
        ),
        migrations.AlterIndexTogether(
            name='rfcstatesummary',
            index_together=set([('oldstate', 'state')]),
        ),
        migrations.CreateModel(
            name='StateByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateField()),
                ('page_count', models.PositiveIntegerField()),
                ('state_id', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='rpc.States')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='statebydate',
            unique_together=set([('state_id', 'state_date')]),
        ),
    ]
