# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0002_auto_20160419_2219_squashed_0004_auto_20160424_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='statebydate',
            name='doc_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statebydate',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
