# Generated by Django 2.2.24 on 2021-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0003_auto_20160508_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfcstatesummary',
            name='iana_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rfcstatesummary',
            name='old_iana_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rfcstatesummary',
            name='old_ref_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rfcstatesummary',
            name='ref_flag',
            field=models.BooleanField(null=True),
        ),
    ]
