From: RFC Editor <rfc-editor@rfc-editor.org>
To: "${name}" <$addr>
Bcc: surveys@rfc-editor.org
Reply-To: RPC Surveys <surveys@rfc-editor.org>
Subject: RFC Editor satisfaction survey for ${month}
Mime-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

This is a survey for authors and shepherds of recently published RFCs.  We've sent you this
because you are:

${rfcs}

We'd appreciate it if you'd complete a short survey about how we did.  
Start the survey here: ${url}

If you authored or shepherded more than one RFC in the past month, please note 
for which RFCs your experience applies in the comments or do the survey again 
to provide separate feedback.  

Regards,

XYZ
Director, RFC Production Center

